services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - backend/.env
    volumes:
      - ./frontend:/frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"
    depends_on:
      - database
    env_file:
      - backend/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./backend:/backend
    restart: on-failure

  database:
    build:
      context: ./backend
      dockerfile: Dockerfile.mysql
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    command: ['mysqld', '--bind-address=0.0.0.0']
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: