version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    ports:
      - "80:80" # Forward port 80 for the nginx server
    depends_on:
      - backend
    env_file: backend/.env
    volumes:
      - ./frontend:/frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000" # Forward port 5000 for the Flask server
    depends_on:
      - database
    env_file: backend/.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./backend:/backend
    restart: on-failure

  database:
    image: mysql/mysql-server # Use the latest MySQL Docker image
    environment:
      MYSQL_ROOT_PASSWORD: root # Set the root password for MySQL
      MYSQL_DATABASE: WikiOfEverything # Set the name of your database
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306" # Forward port 3306 for MySQL
    volumes:
      - ./backend/sql/INIT.SQL:/docker-entrypoint-initdb.d/init.sql
    command: ['mysqld', '--bind-address=0.0.0.0']
