# Use the pytorch/pytorch image as the base image
FROM pytorch/pytorch:latest

# Set the working directory in the container
WORKDIR /backend

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose port 5000 for the Flask server
EXPOSE 5000

# Start the Flask server
CMD ["python", "server.py"]
